import '../../features/realestate_screen/data/models/property_model.dart';

class PropertyData {
  final List<PropertyModel> propertiesList = [
    const PropertyModel(
      id: 1,
      title: "شقة فاخرة في شارع النيل",
      type: "شقة",
      status: "متاحة",
      price: 600000000,
      location: "حلب - شارع النيل",
      size: 150.0,
      bedrooms: 3,
      bathrooms: 2,
      furnished: true,
      description: "شقة مفروشة بالكامل مع إطلالة رائعة، قريبة من الخدمات.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "أحمد المصري",
      dallalPhone: "0944444444",
      listingDate: "2025-03-20",
      verified: true,
      subtitle: '',
      details: '',
    ),
    const PropertyModel(
      id: 2,
      title: "منزل في حي الجميلية",
      type: "شقة",
      status: "مؤجرة",
      price: 400000000,
      location: "حلب - الجميلية",
      size: 130.0,
      bedrooms: 2,
      bathrooms: 1,
      furnished: false,
      description: "شقة واسعة مع تهوية ممتازة، بالقرب من المواصلات العامة.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "سامي قدور",
      dallalPhone: "0955555555",
      listingDate: "2025-03-19",
      verified: false,
      subtitle: '',
      details: '',
    ),
    const PropertyModel(
      id: 1,
      title: "فيلا فاخرة في حلب الجديدة",
      type: "فيلا",
      status: "متاحة",
      price: 3500000000,
      location: "حلب - حلب الجديدة",
      size: 500.0,
      bedrooms: 5,
      bathrooms: 4,
      furnished: true,
      description: "فيلا فاخرة مع مسبح وحديقة واسعة، مثالية للعائلات الكبيرة.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "حسن العلي",
      dallalPhone: "0966666666",
      listingDate: "2025-03-18",
      verified: true,
      subtitle: '',
      details: '',
    ),
    const PropertyModel(
      id: 1,
      title: "محل تجاري في محطة بغداد",
      type: "محل تجاري",
      status: "متاح",
      price: 750000000,
      location: "حلب - محطة بغداد",
      size: 80.0,
      bedrooms: 0,
      bathrooms: 1,
      furnished: false,
      description: "محل تجاري بموقع استراتيجي، مناسب لكافة الأنشطة التجارية.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "خالد عبود",
      dallalPhone: "0933333333",
      listingDate: "2025-03-17",
      verified: true,
      subtitle: '',
      details: '',
    ),
    const PropertyModel(
      id: 1,
      title: "أرض للبيع في حي الفرقان",
      type: "أرض",
      status: "متاحة",
      price: 2000000000,
      location: "حلب - الفرقان",
      size: 700.0,
      bedrooms: 0,
      bathrooms: 0,
      furnished: false,
      description: "أرض استثمارية بموقع مميز، مناسبة للبناء أو المشاريع التجارية.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "محمد ديب",
      dallalPhone: "0922222222",
      listingDate: "2025-03-16",
      verified: false,
      subtitle: '',
      details: '',
    ),
    const PropertyModel(
      id: 1,
      title: "مكتب في السبع بحرات",
      type: "مكتب",
      status: "مؤجر",
      price: 900000000,
      location: "حلب - السبع بحرات",
      size: 120.0,
      bedrooms: 0,
      bathrooms: 2,
      furnished: false,
      description: "مكتب حديث مع تكييف مركزي وإطلالة رائعة على المدينة.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "وليد إبراهيم",
      dallalPhone: "0911111111",
      listingDate: "2025-03-15",
      verified: true,
      subtitle: '',
      details: '',
    ),
    const PropertyModel(
      id: 1,
      title: "شقة مفروشة في حي الميريديان",
      type: "شقة",
      status: "متاحة",
      price: 1100000000,
      location: "حلب - الميريديان",
      size: 160.0,
      bedrooms: 3,
      bathrooms: 2,
      furnished: true,
      description: "شقة مفروشة بالكامل، قريبة من الأسواق والمرافق العامة.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "عمر خليل",
      dallalPhone: "0988888888",
      listingDate: "2025-03-14",
      verified: true,
      subtitle: '',
      details: '',
    ),
    const PropertyModel(
      id: 1,
      title: "منزل في حي السكري",
      type: "شقة",
      status: "متاحة",
      price: 300000000,
      location: "حلب - السكري",
      size: 110.0,
      bedrooms: 2,
      bathrooms: 1,
      furnished: false,
      description: "شقة اقتصادية في حي هادئ، قريبة من المدارس والمواصلات.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "ياسر دياب",
      dallalPhone: "0939999999",
      listingDate: "2025-03-13",
      verified: false,
      subtitle: '',
      details: '',
    ),
    const PropertyModel(
      id: 1,
      title: "فيلا دوبلكس في جمعية الزهراء",
      type: "فيلا",
      status: "متاحة",
      price: 2800000000,
      location: "حلب - جمعية الزهراء",
      size: 450.0,
      bedrooms: 4,
      bathrooms: 3,
      furnished: true,
      description: "فيلا دوبلكس راقية، تشطيب ممتاز وحديقة خاصة.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "ماهر زيدان",
      dallalPhone: "0977777777",
      listingDate: "2025-03-12",
      verified: true,
      subtitle: '',
      details: '',
    ),
    const PropertyModel(
      id: 1,
      title: "شقة واسعة في حي الأعظمية",
      type: "شقة",
      status: "متاحة",
      price: 720000000,
      location: "حلب - الأعظمية",
      size: 180.0,
      bedrooms: 3,
      bathrooms: 2,
      furnished: false,
      description: "شقة كبيرة مع بلكونة واسعة وإطلالة على المدينة.",
      imageUrl: "https://picsum.photos/200/300?houses",
      dallalName: "نزار الحاج",
      dallalPhone: "0941111111",
      listingDate: "2025-03-11",
      verified: true,
      subtitle: '',
      details: '',
    ),
    // يمكنك إضافة المزيد من العقارات بنفس الطريقة...
  ];
}